MIME-Version: 1.0
From: info@netwic.com
To: Emil.Skogsund@gmail.com
Date: Tue, 13 Apr 2021 14:36:24 +0000
Subject: Snart är det sommar!
Message-ID: <eGNTmXmCRUi1F2Of7_wMHg@geopod-ismtpd-6-0>
Content-Type: text/html; charset="us-ascii"

Hej alla!<br /><br />Nu &auml;r det ett tag sedan vi h&ouml;rde av oss. V&aring;rsolen har &auml;ntligen b&ouml;rjat v&auml;rma och vi sitter fortfarande med en hel del fr&aring;gor som saknar svar, men vi planerar f&ouml;r fullt inf&ouml;r sommars&auml;songen.<br />Planeringen h&auml;nger s&aring;klart ihop med n&auml;r vi kan &aring;teruppta normal trafik, och hur m&aring;nga passagerare vi kommer att kunna v&auml;lkomna ombord. Vi ser dock redan nu att vi kommer ha m&ouml;jlighet att erbjuda ett antal arbetspass i Juli och Augusti, b&aring;de kortare och l&auml;ngre.<br />&Auml;r du intresserad av jobb i sommar? G&aring; in i Netwic och g&ouml;r dig tillg&auml;nglig! Om du inte l&auml;ngre &auml;r intresserad av att vara kvar i vikariebanken &ndash; skicka ett mail till oss s&aring; kan vi uppdatera!<br />H&auml;r kommer ocks&aring; information till dig som vill jobba:<br />Giltighetstiden p&aring; l&auml;karintyg har f&ouml;rl&auml;ngts under pandemin:<br />L&auml;karintyg med utg&aring;ngsdatum 1/4-2020 och till 31/5-2021 f&ouml;rl&auml;ngs automatiskt med 15 m&aring;nader dock l&auml;ngst till 30/9-2021. F&ouml;r utg&aring;ngsdatum efter 31/5 g&auml;ller utg&aring;ngsdatum p&aring; intyget.<br />Om du vill jobba i sommar, och beh&ouml;ver f&ouml;rnya ditt intyg s&aring; beh&ouml;ver detta ordnas i god tid innan sommaren. H&ouml;r av dig till oss s&aring; kan vi planera in en tid.<br />Givetvis &auml;r du alltid varmt v&auml;lkommen att h&ouml;ra av dig om stort och sm&aring;tt till oss p&aring; HR. Snabbaste s&auml;ttet att n&aring; oss &auml;r som vanligt via:&nbsp; HRsea.swe@tallinksilja.com<br /><br />P&aring; &aring;terh&ouml;rande!<br /><br />H&auml;lsningar Jessica och Charlotte p&aring; HR Stockholm<br />&nbsp;
