MIME-Version: 1.0
From: info@netwic.com
To: Emil.Skogsund@gmail.com
Date: Wed, 05 Jan 2022 15:07:00 +0000
Subject: Viktig information om Covidtest
Message-ID: <DifUqusMRkKqdEZBrxpeEQ@geopod-ismtpd-2-2>
Content-Type: text/html; charset="us-ascii"

Hejsan alla!<br />&nbsp;<br />I och med att smittspridningen av Covid 19 &auml;r h&ouml;g och p&aring; &ouml;kande inf&ouml;r Tallink Silja AB krav p&aring; testning f&ouml;r att kunna arbeta ombord. Detta g&auml;ller oavsett om du &auml;r vaccinerad eller inte.<br />&nbsp;<br />Testningen sker ombord enligt f&ouml;ljande;<br />&nbsp;<br />F&ouml;r dig som skall m&ouml;nstra p&aring; g&auml;ller att du omedelbart efter ombordstigning g&aring;r till SJS f&ouml;r testning, du f&aring;r inte g&aring; till hytten eller n&aring;gon annanstans innan du testat negativt. Det tar c:a 15 minuter att f&aring; testsvar. Testet &auml;r kostnadsfritt.<br />Vid negativt resultat &auml;r det bara att arbeta p&aring; som vanligt.<br />Vid positivt test skall du l&auml;mna fartyget direkt alternativt g&aring; i karant&auml;n ombord om fartyget redan avg&aring;tt. Du kommer i s&aring;fall isoleras i en hytt och du f&aring;r g&aring; av fartyget n&auml;sta g&aring;ng det ankommer ombordstigningshamnen.<br />&nbsp;<br />F&ouml;r dig som &auml;r ombord redan g&auml;ller att du testar dig hos SJS ombord enligt uppgjort schema, sedan g&auml;ller testet 4 dygn. Efter 96 timmar &auml;r det dags f&ouml;r ett nytt test.<br />Vid negativt resultat &auml;r det bara att arbeta p&aring; som vanligt.<br />Vid positivt test skall du l&auml;mna fartyget direkt alternativt g&aring; i karant&auml;n ombord om fartyget redan avg&aring;tt. Du kommer i s&aring;fall isoleras i en hytt och du f&aring;r g&aring; av fartyget n&auml;sta g&aring;ng det ankommer ombordstigningshamnen.<br />&nbsp;<br />Vi beklagar att vi blivit tvungna att vidta dessa &aring;tg&auml;rder men i och med den stora smittspridningen just nu s&aring; vill vi minimera att det blir ett stort utbrott av smitta ombord, och hoppas ni har &ouml;verseende med den ol&auml;genhet detta medf&ouml;r.<br />&nbsp;<br />Mvh<br />HR Avdelningen, Tallink Silja<br />&nbsp;
