MIME-Version: 1.0
From: info@netwic.com
To: Emil.Skogsund@gmail.com
Date: Thu, 19 Nov 2020 09:05:05 +0000
Subject: Hälsningar från oss
Message-ID: <FVlQ_ByrQN-lmIP5qpcW5g@ismtpd0004p1lon1.sendgrid.net>
Content-Type: text/html; charset="us-ascii"

Hej alla!<br /><br />Nu var det ett tag sedan vi h&ouml;rde av oss. Vi l&auml;ngtar ju efter att kunna komma med lite positiva nyheter &ndash; men de lyser ju tyv&auml;rr med sin fr&aring;nvaro.<br />H&ouml;sten har varit m&ouml;rk och l&aring;ng &ndash; och vintern ser inte ut att vara s&aring; mycket ljusare. Galaxy &auml;r fortfarande i trafik men med minimal bemanning och v&auml;ldigt f&aring; passagerare. Symphony har &aring;kt p&aring; n&aring;gra h&ouml;stlovskryssningar till H&ouml;ga Kusten vilka har varit v&auml;ldigt uppskattade.<br />Som ni har h&ouml;rt i media &auml;r ju restriktionerna nu &auml;nnu h&aring;rdare och vi m&aring;ste anpassa oss efter det regelverk som finns. Viktigast nu &auml;r att alla h&aring;ller sig friska och g&ouml;r allt f&ouml;r att inte sprida smittan vidare.<br />Det vi kan se fram emot &auml;r att det kommer en tid efter pandemin. D&aring; hoppas och tror vi att m&auml;nniskor har en l&auml;ngtan efter att komma ut och se v&auml;rlden igen &ndash; och d&aring; passar ju v&aring;ra kryssningar utm&auml;rkt! S&aring; inf&ouml;r n&auml;sta sommars&auml;song hoppas vi verkligen att vi ska ta oss upp ur krisen.<br />Tack f&ouml;r alla mail och fr&aring;gor vi f&aring;r fr&aring;n er! Det &auml;r s&aring; roligt att kunna ha lite kontakt &ndash; trots att vi inte kan ge n&aring;gra glada besked eller jobb p&aring; b&aring;tarna f&ouml;r n&auml;rvarande.<br />Vi kommer att informera n&auml;r vi b&ouml;rjar se ett behov av vikarier igen &ndash; och d&aring; ocks&aring; uppmuntra dig att g&ouml;ra dig tillg&auml;nglig. &Auml;r det s&aring; att du har f&aring;tt annat f&ouml;r dig och inte l&auml;ngre &auml;r intresserad av att vara kvar i v&aring;r vikariebank skulle vi vara glada om du meddelar oss.<br />Givetvis &auml;r du alltid varmt v&auml;lkommen att h&ouml;ra av dig till oss p&aring; HR. Vi &auml;r oftast inte p&aring; plats samtidigt s&aring; det snabbaste s&auml;ttet att n&aring; oss &auml;r som vanligt via:&nbsp; HRsea.swe@tallinksilja.com<br /><br />P&aring; &aring;terh&ouml;rande!<br />Jessica och Charlotte p&aring; HR - avdelningen<br />&nbsp;
