MIME-Version: 1.0
From: Club One <no-reply@messages.tallinksilja.se>
To: emil.skogsund@gmail.com
Date: Tue, 19 May 2020 10:29:28 +0100
Subject: Ett meddelande från vår CEO
Message-ID: <AC7000000000E4CFB1F0DB9585Ctallink_mkt_prod6@messages.tallinksilja.se>
Content-Type: multipart/alternative; boundary="----=_NextPart_734_4707FE44.4707FE44"

Jag hoppas innerligt att du – och dina nära och kära – har mått bra och varit friska den senaste månaden. Vi på Tallinks huvudkontor har tänkt mycket på dig och det centrala för oss just nu är vår omsorg om välbefinnande, hälsa och säkerhet för dig, våra anställda och för samhället i sin helhet. Vi har också givetvis fokuserat på annat, men jag lovar dig att denna omsorg har genomsyrat alla våra konversationer, planer och tankar om utveckling.När den pandemiska situationen på våra hemmamarknader fortsätter att förbättras dag för dag, börjar vi försiktigt tro att det finns hopp om att vi, inom en snar framtid, återigen kan erbjuda åtminstone några av våra tjänster och att de vita fartygen snart seglar på den vackra blåa Östersjön igen. Förra veckan såg vi den första betydande milstolpen när vissa typer av resor för pendlare, och andra, återupptogs på rutten Tallinn-Helsingfors den 14 maj. Vi följer strikt myndigheternas 
rekommendationer och vidtar flera förebyggande åtgärder för att bekämpa viruset. Genom detta är vi oerhört hoppfulla över att vi kan bevisa att det är möjligt att resa på ett säkert sätt och så att fler gränser och dörrar gradvis kommer att öppnas som ett resultat av detta. Även för dem som vill göra semesterresor på fritiden. Vi tror att det kommer att vara möjligt om vi alla tar ansvar och jobbar tillsammans. Och förhoppningsvis att detta blir möjligt redan i sommar.  Från vår sida har vi förberett oss, diskuterat med experter och redan nu infört några av de första åtgärderna för ännu säkrare, tryggare resor. Några av dessa steg inkluderar att tillfälligt minska antalet passagerare som vi tillåter ombord per avgång – för att säkerställa att vi kan hålla ett säkert avstånd. Vi har installerat tillfälliga plexiglasväggar vid kassorna i våra butiker ombord och vid våra informationsdiskar. Vi har gjort ändringar i hur vi serverar mat 
ombord. Vi har tillfälligt stängt barnens lekytor och bollhav. Vi uppmuntrar våra passagerare att använda våra onlinetjänster för bokningar och incheckning mer än tidigare. Vi ber kunderna bekräfta att de är friska när de gör en bokning. Vi letar efter fler sätt att erbjuda våra tjänster kontaktlöst där det är möjligt. Allt med ditt bästa i åtanke. Detta är bara några av de åtgärder vi har genomfört, det finns många fler som du kan läsa om på vår webb.  Nyckeln till framgång och ytterligare lättnader av begränsningarna, är samarbete och gemensamma kraftansträngningar för bekämpa detta virus. Vi måste alla ta vårt ansvar och göra vårt bästa för att följa de rådande reglerna och TILLSAMMANS kan vi säkerställa att vi kan fortsätta att segla in i framtiden.Vi frågade nyligen några av er om ni planerar att resa någonstans i sommar, under dessa utmanande tider. Ert svar var ett rungande ja till att återvända till havet och ta minst 
några korta resor till grannländerna redan i sommar, om det är möjligt. Vi gör vårt bästa för att säkerställa att detta händer – genom att öka tryggheten, genom att samarbeta och bevisa att vi tar detta med säkerhet på extremt stort allvar. Hela teamet här på Tallink arbetar hårt med att säkerställa att dina resor med oss kommer att vara lika bekväma, trevliga, avkopplande och minnesvärda som de alltid har varit, trots en förändrad resevärld. Våra fartyg är stora, cirka 200 meter långa, de flesta med mer än 10 däck, så det är möjligt att distansera sig socialt från andra ombord, samtidigt som du kan arbeta, vila eller bara njuta av havsutsikten. Vi har verkligen saknat dig de senaste månaderna, men vi gör oss redo och väntar på dig när det är dags kliva ombord igen, kära vänner. Till dess, håll dig frisk och ta hand om dig. Vi har saknat dig.
Paavo NõgeneCEO, Tallink Grupp
